config/routes.rb
Rails.application.routes.draw do
	devise_for :users, controllers: {
    registrations: 'registrations',
    confirmations: 'confirmations',
    sessions: 'sessions'
  }
  root 'statements#index'

  post :accept_agreement, controller: 'application'

  devise_scope :user do
    get 'users/confirmation_sent', to: 'confirmations#confirmation_sent', as: 'confirmation_sent'
    get 'users/smart_auth', to: 'sessions#smart_auth', as: 'smart_auth'
  end

  resources :arguments do
    member do
      post :publish
      post :upvote
      post :remove_vote
      get :suggest_new
    end
  end

  resources :statements do
    member do
      get :new_response
      post :agree
      post :disagree
      post :no_stance
      get :agreements
      get :disagreements
      post :review_arguments
    end
  end

  get 'arguments/:id/counter', to: 'counters#new', as: 'new_counter_argument'
  post 'arguments/:id/counter', to: 'counters#create', as: 'create_counter_argument'
end

app/models/argument.rb
class Argument < ApplicationRecord
  include UUID

  belongs_to :user

  belongs_to :subject_statement, class_name: 'Statement', optional: true

  # An argument can address its parent argument
  belongs_to :parent_argument, class_name: 'Argument', optional: true
  has_many :child_arguments, dependent: :destroy, class_name: 'Argument', foreign_key: :parent_argument_id

  # temporary to enable migration
  has_many :premises

  has_many :votes,    dependent: :destroy
  has_many :counters, dependent: :destroy, class_name: 'Statement', foreign_key: :countered_argument_id

  validates_inclusion_of :agree, in: [true, false]
  validate :has_subject

  after_create :upvote_if_applicable

  def self.published
    where.not(published_at: nil)
  end

  def self.top_level
    where(parent_argument_id: nil)
  end

  def self.visible_to_user(user)
    where('published_at is not null or arguments.user_id = ?', user.id)
  end

  def self.vote_order
    # Sort by number of votes and then by state priority.
    joins('LEFT JOIN votes ON votes.argument_id = arguments.id').group('arguments.id').order('count(votes.id) desc').sort_by(&:state_priority)
  end

  def input_placeholder
    "Why do you #{agree ? 'support' : "disagree with" } this statement?"
  end

  def type
    return 'clarification' if parent_argument
    agree ? 'supporting argument' : 'counterargument'
  end

  def agree_disagree(context = nil)
    word = agree ? 'agree' : 'disagree'

    if context.is_a?(User) && context != user
      word + 's'
    else
      word
    end
  end

  def actionable_to_user?(user)
    published? && self.user != user && subject.stance_of(user).present?
  end

  def prompt_user_for_stance?(user)
    published? && self.user != user && !subject.stance_of(user).present?
  end

  def subject
    subject_statement || Statement.new(text: '(No subject)')
  end

  def publish!
    touch(:published_at)
    notify_previous_user
  end

  def published?
    published_at.present?
  end

  def win?
    counters.none?(&:win?)
  end

  def lose?
    counters.any?(&:win?)
  end

  def state
    return 'Unaddressed' if counters.none?
    return 'Supported' if counters.none?(&:win?)
    'Countered'
  end

  def state_priority
    case state
    when 'Supported' then 0
    when 'Unaddressed' then 1
    when 'Countered' then 2
    end
  end

  def icon
    return 'checkmark' if win?
    return 'x' if lose?
    'question'
  end

  def breadcrumbs
    subject.breadcrumbs.concat([subject])
  end

  private

  def wordmap(text)
    Hash[text.words.map { |word| [word, nil] }]
  end

  def has_subject
    errors.add(:base, 'Must have subject statement') unless subject.present?
  end

  def upvote_if_applicable
    if Vote.where(user: user, argument: self).none?
      Vote.create(user: user, argument: self)
    end
  end

  def notify_previous_user
    ActivityNotificationMailer.notify_reply(self).deliver_now
  end
end

app/controllers/arguments_controller.rb
class ArgumentsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_argument, only: [:show, :edit, :update, :publish, :upvote, :remove_vote, :destroy, :suggest_new, :counter]
  before_action :new_argument, only: [:new, :create]
  after_action :publish_from_form, only: [:create, :update]

  # GET /arguments
  # GET /arguments.json
  def index
    redirect_to statements_path
  end

  # GET /arguments/1
  # GET /arguments/1.json
  def show
  end

  def suggest_new
    parent_argument = @argument
    @argument = @argument.dup
    @argument.parent_argument = parent_argument
    @argument.user = current_user
    @argument.published_at = nil
    @argument.set_uuid
  end

  # GET /arguments/new
  def new
  end

  # GET /arguments/1/edit
  def edit
  end

  # POST /arguments
  # POST /arguments.json
  def create
    ActiveRecord::Base.transaction do
      respond_to do |format|
        if !@argument.save
          format.html { render :new, alert: 'Failed to create argument.' }
          format.json { render json: @argument.errors, status: :unprocessable_entity }
        else
          format.html { redirect_to @argument }
          format.json { render :show, status: :created, location: @argument }
        end
      end
    end
  end

  # PATCH/PUT /arguments/1
  # PATCH/PUT /arguments/1.json
  def update
    ActiveRecord::Base.transaction do
      respond_to do |format|
        if !@argument.update(argument_params)
          format.html { render :edit, alert: 'Failed to update argument.' }
          format.json { render json: @argument.errors, status: :unprocessable_entity }
        else
          format.html { redirect_to @argument }
          format.json { render :show, status: :ok }
        end
      end
    end
  end

  def publish
    @argument.publish!
    redirect_to @argument
  end

  def upvote
    Vote.create(argument: @argument, user: current_user)
    redirect_to @argument.subject
  end

  def remove_vote
    Vote.find_by(argument: @argument, user: current_user).destroy
    redirect_to @argument.subject
  end

  def counter
    @statement = Statement.new(countered_argument_id: @argument.id)
  end

  # DELETE /arguments/1
  # DELETE /arguments/1.json
  def destroy
    @argument.destroy
    respond_to do |format|
      format.html { redirect_to arguments_url, notice: 'Argument was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def find_argument
      @argument = Argument.find(params[:id])
    end

    def new_argument
      @argument = Argument.new(argument_params.merge(user: current_user))
    end

    def argument_params
      params.require(:argument).permit(:uuid, :text, :agree, :subject_statement_id, :parent_argument_id)
    end

    def save_action
      params.permit(:save_action).fetch(:save_action, nil)
    end

    def after_update_view
      case save_action
      when 'publish'
        @argument.subject
      else
        argument_path(@argument)
      end
    end

    def publish_from_form
      @argument.publish! if save_action == 'publish'
    end
end

app/helpers/arguments_helper.rb
module ArgumentsHelper
end

app/views/arguments/_body.html.erb
<%= render 'arguments/heading', argument: argument %>
<%= render 'arguments/content', argument: argument.parent_argument if argument.parent_argument.present? %>
<%= render 'arguments/content', argument: argument %>

app/views/arguments/_content.html.erb
<p class="argument-explanation">
  <% if argument.parent_argument.present? && !local_assigns[:no_recurse] %>
    <%= my(argument) ? 'You interpret' : "#{argument.user.username} interprets" %>
    <%= link_to(my(argument.parent_argument) ? 'your argument' : "#{argument.parent_argument.user.username}'s argument", argument.parent_argument) %> as follows:
  <% else %>
    <%= my(argument) ? 'Your' : "#{argument.user.username}'s" %> <%= argument.agree ? 'supporting ' : 'counter' %>argument:
  <% end %>
</p>

<p><%= argument.text %></p>

app/views/arguments/_footer.html.erb
<span class="date">
  <% if argument.published? %>
    Published <%= I18n.l argument.published_at %>
  <% else %>
    Not yet published
  <% end %>
</span>

app/views/arguments/_form.html.erb
<%= form_for(@argument) do |f| %>
  <% if @argument.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@argument.errors.count, "error") %> prohibited this argument from being saved:</h2>
      <ul>
      <% @argument.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <% if local_assigns[:suggest_new] %>
      Without changing the argument's meaning, adjust the words to show how you interpret the original argument.
    <% else %>
      <%= @argument.input_placeholder %>
    <% end %>
  </p>

  <%= f.text_area :text, style: "width: 100%; height: 40px; font-family: Verdana;" %>

  <div class="argument-actions">
    <button type="submit" name="save_action" value="publish">Publish</button>
    <button type="submit" name="save_action" value="save_draft" class="secondary">Save Draft</button>
    <%= link_to 'Cancel', @argument.subject %>
  </div>

  <%= f.number_field :parent_argument_id, hidden: true %>
  <%= f.number_field :subject_statement_id, hidden: true %>
  <%= f.text_field :uuid, hidden: true %>
  <%= f.check_box :agree, hidden: true %>
<% end %>

app/views/arguments/_heading.html.erb
<p class="context">(Regarding: <%= link_to argument.subject.text, argument.subject %>)</p>

app/views/arguments/_premises.html.erb
<p class="argument-explanation">
  <% if argument.parent_argument.present? && !local_assigns[:no_recurse] %>
    <%= my(argument) ? 'You interpret' : "#{argument.user.username} interprets" %>
    <%= link_to(my(argument.parent_argument) ? 'your argument' : "#{argument.parent_argument.user.username}'s argument", argument.parent_argument) %> as follows:
  <% else %>
    <%= my(argument) ? 'Your' : "#{argument.user.username}'s" %> <%= argument.agree ? 'supporting ' : 'counter' %>argument:
  <% end %>
</p>

<% if argument.premises.any? %>
  <ul class="premises-list">
    <% argument.premises.each do |p| %>
      <li><%= p.text %></li>
    <% end %>
  </ul>
<% else %>
  <p>No premises given.</p>
<% end %>

app/views/arguments/_publish_date.html.erb
<span class="date">
  <% if argument.published? %>
    Published <%= I18n.l argument.published_at %>
  <% else %>
    Not yet published
  <% end %>
</span>

app/views/arguments/counter.html.erb
<%= render 'body', argument: @statement.countered_argument %>

<%= form_for(@statement) do |f| %>
  <% if @statement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@statement.errors.count, "error") %> prohibited this @statement from being saved:</h2>

      <ul>
        <% @statement.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <br />

  <label for="text">What is the problem with this argument? <br /><i>Summarize in one statement. Further discussion is possible later.</i></label>

  <div class="field">
    <%= f.text_field :text, class: 'statement-line' %>
  </div>

  <%= f.number_field :countered_argument_id, hidden: true %>

  <div class="argument-actions">
    <%= f.submit "Publish" %>
    <%= link_to 'Cancel', argument_path(@statement.countered_argument) %>
  </div>
<% end %>

app/views/arguments/edit.html.erb
<%= render 'heading', argument: @argument %>
<%= render 'form', argument: @argument %>

app/views/arguments/new.html.erb
<%= render 'heading', argument: @argument %>
<%= render 'form', new_statement: true %>

app/views/arguments/show.html.erb
<%= render 'shared/breadcrumbs', context: @argument %>

<p class="statement-heading"><%= @argument.text %></p>
<%= render 'statements/state', subject: @argument %>
<%= render 'statements/date_and_author', subject: @argument %>
<span class="argument-explanation meta-text">(<%= @argument.type %>)</span>

<% if @argument.child_arguments.present? %>
  <p>Replies:
    <% @argument.child_arguments.map do |child| %>
      &nbsp; <%= link_to "#{child.user.username}'s clarification", child %>
    <% end %>
  </p>
<% end %>

<% if @argument.prompt_user_for_stance? current_user %>
  <p>To address this argument, please first indicate your stance on <%= link_to 'the subject', @argument.subject %>.</p>
<% end %>

<div class="argument-actions">
  <% if my(@argument) && !@argument.published? %>
    <%= button_to 'Publish', publish_argument_path(@argument) %>
    <%= link_to 'Edit', edit_argument_path(@argument), class: 'btn' %>
  <% end %>
  <% if @argument.actionable_to_user? current_user %>
    <%= link_to 'Counter', new_counter_argument_path(@argument), class: 'btn' %>
    <%= link_to 'Clarify', suggest_new_argument_path(@argument), class: 'btn' if Rails.env.test? %>
  <% end %>
  <% if @argument.parent_argument.present? %>
  <%= link_to 'Back to parent argument', @argument.parent_argument, class: 'btn' if Rails.env.test? %>
  <% end %>
</div>

<br />

<% if @argument.counters.any? %>
  <p><strong>Counters</strong></p>
    <% @argument.counters.map do |counter| %>
      <div class="argument">
        <div class="argument-oneline"><%= link_to counter.text, statement_path(counter.id) %></div>
        <%= render 'statements/state', subject: counter %>
        <%= render 'statements/date_and_author', subject: counter %>
      </div>
    <% end %>
  </div>
<% end%>

app/views/arguments/suggest_new.html.erb
<%= render 'heading', argument: @argument %>
<%= render 'form', suggest_new: true %>