config/routes.rb
Rails.application.routes.draw do
	devise_for :users, controllers: {
    registrations: 'registrations',
    confirmations: 'confirmations',
    sessions: 'sessions'
  }
  root 'statements#index'

  post :accept_agreement, controller: 'application'

  devise_scope :user do
    get 'users/confirmation_sent', to: 'confirmations#confirmation_sent', as: 'confirmation_sent'
    get 'users/smart_auth', to: 'sessions#smart_auth', as: 'smart_auth'
  end

  resources :arguments do
    member do
      post :publish
      post :upvote
      post :remove_vote
      get :suggest_new
    end
  end

  resources :statements do
    member do
      get :new_response
      post :agree
      post :disagree
      post :no_stance
      get :agreements
      get :disagreements
      post :review_arguments
    end
  end

  get 'arguments/:id/counter', to: 'counters#new', as: 'new_counter_argument'
  post 'arguments/:id/counter', to: 'counters#create', as: 'create_counter_argument'
end

app/models/statement.rb
class Statement < ApplicationRecord
  include UUID

  belongs_to :user

  has_many :arguments, dependent: :destroy, foreign_key: :subject_statement_id
  has_many :stances, dependent: :destroy

  before_validation :strip_text_whitespace
  before_validation :add_period

  belongs_to :countered_argument, class_name: 'Argument', optional: true

  validates_presence_of :text

  validate :one_statement, on: :create
  attr_accessor :verified_one_sentence

  after_create :notify_previous_user

  def subject
    countered_argument
  end

  # For now, mask the fact that there is no separate publish date.
  def published_at
    created_at
  end

  def words
    text.split(' ').map(&:strip)
  end

  def stance_of(user)
    return Stance.new(user: user, statement: self, agree: true) if user == self.user
    Stance.find_by(user: user, statement: self)
  end

  def agreed_by?(user)
    return true if user == self.user
    stance_of(user)&.agree
  end

  def allow_action?(user)
    stance_of(user).present? || user == self.user
  end

  def last_argument_by(user)
    arguments.where(user: user).last
  end

  def nested
    countered_argument.present?
  end

  def win?
    @win ||= begin
      return true if nested && disagreements.none? && agreements.none?
      # TODO: scope to top-voted arguments for sanity
      disagreements.none?(&:win?) && agreements.any?(&:win?)
    end
  end

  def lose?
    @lose ||= agreements.none?(&:win?) && disagreements.any?(&:win?)
  end

  def state
    return 'Unaddressed' if arguments.count == 0
    return 'Supported' if win?
    return 'Countered' if lose?
    'Disputed'
  end

  def icon
    return 'checkmark' if win?
    return 'x' if lose?
    'question'
  end

  def sentence_split
    text.strip.scan(/[^.!?]+[.!?]+\s*/).map(&:strip)
  end

  def likely_multiple_statements?
    sentence_split.count > 1
  end

  def breadcrumbs
    return [] unless countered_argument.present?
    countered_argument.breadcrumbs.concat([countered_argument])
  end

  private

  def agreements
    arguments.published.top_level.where(agree: true)
  end

  def disagreements
    arguments.published.top_level.where(agree: false)
  end

  def strip_text_whitespace
    text.strip!
  end

  def add_period
    self.text += '.' if text.present? && !(text[-1] =~ /[.!?]/)
  end

  def one_statement
    errors.add(:base, 'Please verify that this is only one sentence.') if likely_multiple_statements? && verified_one_sentence != '1'
  end

  def notify_previous_user
    ActivityNotificationMailer.notify_reply(self).deliver_now
  end
end

app/controllers/statements_controller.rb
class StatementsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_statement, only: [:show, :edit, :update, :destroy, :agree, :disagree, :no_stance, :agreements, :disagreements, :review_arguments]
  before_action :find_stance, only: [:show, :edit, :agree, :disagree, :agreements, :disagreements, :review_arguments]

  # GET /statements
  # GET /statements.json
  def index
    @statements = Statement.where(top_level: true)
  end

  # GET /statements/1
  # GET /statements/1.json
  def show
  end

  # GET /statements/new
  def new
    @statement = Statement.new
  end

  def new_response
    allowed_params = params.permit(:id, :agree, :statement)
    @statement = Statement.new(parent_statement_id: allowed_params[:id], agree: allowed_params[:agree] == 'true')
    render :new
  end

  # GET /statements/1/edit
  def edit
  end

  # POST /statements
  # POST /statements.json
  def create
    @statement = Statement.new(statement_params)
    @statement.user = current_user

    respond_to do |format|
      if @statement.save
        format.html { redirect_to @statement, notice: 'Statement was successfully created.' }
        format.json { render :show, status: :created, location: @statement }
      else
        format.html { render :new }
        format.json { render json: @statement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statements/1
  # PATCH/PUT /statements/1.json
  def update
    respond_to do |format|
      if @statement.update(statement_params)
        format.html { redirect_to @statement, notice: 'Statement was successfully updated.' }
        format.json { render :show, status: :ok, location: @statement }
      else
        format.html { render :edit }
        format.json { render json: @statement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statements/1
  # DELETE /statements/1.json
  def destroy
    @statement.destroy
    respond_to do |format|
      format.html { redirect_to statements_url, notice: 'Statement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def agree
    Stance.new(statement: @statement, user: current_user, agree: true).save
    redirect_to agreements_statement_path(@statement)
  end

  def disagree
    Stance.new(statement: @statement, user: current_user, agree: false).save
    redirect_to disagreements_statement_path(@statement)
  end

  def no_stance
    Stance.where(statement: @statement, user: current_user).first&.destroy
    redirect_to @statement
  end

  def agreements
    @side = true
    existing_arguments(@side)
  end

  def disagreements
    @side = false
    existing_arguments(@side)
  end

  def existing_arguments(side)
    if @statement.arguments.where(agree: @side).published.any?
      render :arguments
    else
      redirect_to new_argument_path(@statement, argument: { subject_statement_id: @statement.id, agree: @side })
    end
  end

  def review_arguments
    review_params.fetch(:arguments, {}).each do |argument_id, value|
      next unless value == '1' && argument = Argument.find(argument_id)
      Vote.create(user: current_user, argument: argument)
    end

    if review_params[:other].present?
      redirect_to new_argument_path(@statement, argument: { subject_statement_id: @statement.id, agree: review_params[:agree].to_i == 1 })
    else
      redirect_to @statement
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def find_statement
      @statement = Statement.find(params[:id])
    end

    def find_stance
      @stance = Stance.where(user: current_user, statement: @statement).first
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def statement_params
      params.require(:statement).permit(:uuid, :text, :user_id, :parent_statement_id, :agree, :countered_argument_id, :top_level, :verified_one_sentence)
    end

    def review_params
      params.permit(:agree, :other, :arguments => @statement.arguments.map(&:id).map(&:to_s))
    end
end

app/helpers/statements_helper.rb
module StatementsHelper
end

app/views/statements/_date_and_author.html.erb
<% if date = subject.try(:published_at) %>
  <span class="date">
    <span><%= "(#{subject.votes.count})" unless Rails.env.production? || subject.try(:votes).nil? %></span>
    <span title="<%= I18n.l date %>">submitted <%= time_ago_in_words(date) %> ago</span>
    <span>by <%= subject.user&.username %></span>
  </span>
<% else %>
  <span class="alert">
    SAVED AS DRAFT
  </span>
<% end %>

app/views/statements/_form.html.erb
<%= form_for(statement) do |f| %>
  <p>What do you wish to persuade others is true?</p>
  <div class="field">
    <%= f.text_field :text, class: 'statement-line', onkeyup: 'showHideVerifyCheckbox()' %>
  </div>


  <%= f.text_field :uuid, hidden: true %>

  <div class="verify-sentence">
    <p>Looks like you may have entered more than one sentence. Please remove any unnecessary punctuation, adjust wording, or verify that this is one sentence.</p>
    <label class="verify-sentence">
      <%= f.check_box :verified_one_sentence, class: 'verify-sentence' %>
      <span>This is one sentence.</span>
    </label>
  </div>

  <script>
    function showHideVerifyCheckbox() {
      if ($('.statement-line').val()
           .split(/[.!?]/).map(function(s) { return s.trim() })
           .filter(function(s) { return s.length > 0 })
           .length > 1) {
        $('.verify-sentence').show()
      } else {
        $('.verify-sentence').hide()
      }
    }

    showHideVerifyCheckbox();
  </script>

  <% if statement.errors.any? %>
    <p style="color: red" class="errors"><%= statement.errors.full_messages.join(', ') %></p>
  <% end %>

  <%= f.check_box :top_level, hidden: true, checked: true %>

  <div class="argument-actions">
    <%= f.submit "Publish" %>
    <%= link_to 'Back', statements_path %>
  </div>
<% end %>

app/views/statements/_heading.html.erb
<p class="statement-heading"><%= statement.text %></p>

app/views/statements/_state.html.erb
<span class="state-indicator">
  <img src="/images/<%= subject.icon %>.png" alt="" class="<%= local_assigns[:size] %>" />
  <%= subject.state %>
</span>

app/views/statements/arguments.html.erb
<% if @statement.countered_argument.present? %>
  <p class="countered-argument">Countering argument: <%= link_to @statement.countered_argument.text, @statement.countered_argument %></p>
<% end %>

<p class="statement-heading"><%= @statement.text %></p>
<%= render 'state', subject: @statement %>

<br /><br />

<form action="<%= review_arguments_statement_path(@statement) %>" method="post">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <input type="hidden" name="agree" value="<%= @side ? 1 : 0 %>">
  <% if (arguments = @statement.arguments.where(agree: @side, parent_argument_id: nil).published.vote_order).any? %>
    <p>Which of these reflect your reasons for <%= @side ? 'agree' : 'disagree' %>ing?
    <ul class="checkbox-list">
    <% arguments.each do |argument| %>
      <% param = "arguments[#{argument.id}]" %>
      <li>
        <label>
          <input type="checkbox" name="<%= param %>" value="1">
          <%= argument.text %>
        </label>
      </li>
    <% end %>
      <li>
        <label>
          <input type="checkbox" name="other" value="1">
          Other
        </label>
      </li>
    </ul>
    <br />
    <div class="argument-actions">
      <input type="submit" value="Next">
      <input type="submit" value="Cancel" class="link-button">
    </div>
  <% else %>
    <p>No responses.</p>
  <% end %>
</form>

app/views/statements/edit.html.erb
<h1>Editing Statement</h1>

<%= render 'form', statement: @statement %>

<%= link_to 'Show', @statement %> |
<%= link_to 'Back', statements_path %>

app/views/statements/index.html.erb
<table class="statements-index">
  <tbody>
    <% @statements.each do |statement| %>
      <tr>
        <td>
          <p class="statement-heading"><%= link_to statement.text, statement %></p>
          <%= render 'state', subject: statement %>
          <%= render 'date_and_author', subject: statement %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Statement', new_statement_path %>

app/views/statements/new.html.erb
<%= render 'form', statement: @statement %>

app/views/statements/show.html.erb
<%= render 'shared/breadcrumbs', context: @statement %>

<p class="statement-heading"><%= @statement.text %></p>
<%= render 'state', subject: @statement %>
<%= render 'date_and_author', subject: @statement %>

<div class="stance argument-actions">
  <% if @statement.user == current_user %>
    <span class="date">Published by you</span>. &nbsp;
    <%= link_to "Support your statement", new_argument_path(argument: { subject_statement_id: @statement, agree: true }), class: 'btn' %>
  <% else %>
    <% if @stance %>
      You <%= @stance %>. &nbsp;
      <%= button_to 'Change your stance', no_stance_statement_path(@statement), class: 'link-button small-button' %>
      <%= link_to "New #{@stance.agree ? '' : 'counter'}argument", new_argument_path(argument: { subject_statement_id: @statement, agree: @stance.agree }), class: 'btn' %>
    <% else %>
      <%= button_to 'Agree', agree_statement_path(@statement), class: 'green' %>
      &nbsp;
      <%= button_to 'Disagree', disagree_statement_path(@statement), class: 'red' %>
    <% end %>
  <% end %>
</div>
<br />

<div class="arguments-table">
  <% [true, false].each do |side| %>
    <div class="agree-<%= side %>">
      <p><strong><%= side ? 'Supporting arguments' : 'Counterarguments' %></strong></p>
      <% if (arguments = @statement.arguments.where(agree: side, parent_argument_id: nil).visible_to_user(current_user).vote_order).any? %>
        <% arguments.each do |argument| %>
          <div class="argument">
            <div class="argument-oneline"><%= link_to argument.text, argument %></div>
            <%= render 'state', subject: argument, size: 'small' %>
            <%= render 'date_and_author', subject: argument %>
            <div class="item-actions">
              <% if argument.counters.any? %>
                <span>↳ <%= link_to pluralize(argument.counters.count, 'reply'), argument %></span>
              <% end %>
              <% if @statement.agreed_by?(current_user) == side && argument.user != current_user %>
                <% if current_user.upvoted_argument?(argument) %>
                  You upvoted this. <%= button_to 'Remove upvote', remove_vote_argument_path(argument), class: 'link-button small-button' %>
                <% else %>
                  <%= button_to 'Upvote', upvote_argument_path(argument), class: 'link-button small-button' %>
                <% end %>
              <% elsif @statement.agreed_by?(current_user) == !side %>
                <%= link_to 'Counter', new_counter_argument_path(argument) %>
              <% end %>
            </div>
          </div>
        <% end %>
      <% else %>
        <p>No responses.</p>
      <% end %>
      <br />
    </div>

  <% end %>
</div>